### ISSUE TITLE
Not working with ATMega328P SMD Custom board

### ISSUE THREAD

**Issue by suyashrai** [Yveaux/TDC1000#3]

**Comment by Yveaux** [comment]
The begin() call, which returns false in your case, initializes SPI, resets the TDC1000 and then reads some registers and compares them to default to check if the communication is working as expected.
(Ref: https://github.com/Yveaux/TDC1000/blob/master/TDC1000.cpp#L170)
The TDC1000 driver uses standard SPI. Are you passing the correct CS and reset lines?
You could modify the code and see what values are returned by the spiReadReg8 calls that seem to fail.

**Comment by dsuyashrai** [comment]
Can you please help and suggest what would be the correct CS and Reset Lines and how to find which one is correct?

**Comment by dsuyashrai** [comment]
Hi, thanks for your help. I tried printing the values and the values were as follows:

 **Serial.println(spiReadReg8(TDC1000_REG_ADR_CONFIG_0));** --> _6_
 **Serial.println(TDC1000_REG_DEFAULTS_CONFIG0);** --> _69_
 **Serial.println(spiReadReg8(TDC1000_REG_ADR_CONFIG_1));** --> _64_
 **Serial.println(TDC1000_REG_DEFAULTS_CONFIG1);** --> _64_

Can you please help what might be wrong here?

**Comment by dsuyashrai** [comment]
Hi, could you please help? I'm not to proceed further than this. Any help would be much appreciated.

**Comment by dsuyashrai** [comment]
Hi, 
I just realized it was as simple as removing that library. It has proceeded further now but now there's some other issue. It's showing timeout now.

13:04:49.922 -> -- Starting TDC1000 test --
13:04:50.058 -> 6
13:04:50.058 -> 69
13:04:50.058 -> 64
13:04:50.058 -> 64
13:04:50.058 -> TDC1000 init OK
13:04:50.058 -> T0:				12.50 us
13:04:50.058 -> T1:				25.00 us
13:04:50.058 -> TX_CLOCK:			40000.00 Hz
13:04:50.058 -> CONFIG_0
13:04:50.058 -> 	RAW:			0x6
13:04:50.058 -> 	TX_FREQ_DIV:		2
13:04:50.058 -> 	NUM_TX:			6
13:04:50.058 -> CONFIG_1
13:04:50.058 -> 	RAW:			0x40
13:04:50.058 -> 	NUM_AVG:		1
13:04:50.058 -> 	NUM_RX:			0
13:04:50.058 -> CONFIG_2
13:04:50.058 -> 	RAW:			0x22
13:04:50.058 -> 	VCOM_SEL:		INT
13:04:50.058 -> 	MEAS_MODE:		TOF
13:04:50.058 -> 	DAMPING:		ON
13:04:50.058 -> 	CH_SWP:			OFF
13:04:50.058 -> 	EXT_CHSEL:		OFF
13:04:50.058 -> 	CH_SEL:			1
13:04:50.058 -> 	TOF_MEAS_MODE:		2
13:04:50.058 -> CONFIG_3
13:04:50.058 -> 	RAW:			0x4
13:04:50.058 -> 	TEMP_MODE:		REF, RTD1, RTD2
13:04:50.058 -> 	TEMP_RTD_SEL:		PT1000
13:04:50.058 -> 	TEMP_CLK_DIV:		8
13:04:50.058 -> 	BLANKING:		OFF
13:04:50.058 -> 	ECHO_QUAL_THLD:		-220 mV
13:04:50.058 -> CONFIG_4
13:04:50.058 -> 	RAW:			0x1F
13:04:50.058 -> 	RECEIVE_MODE:		SINGLE ECHO
13:04:50.058 -> 	TRIG_EDGE_POLARITY:	RISING
13:04:50.058 -> 	TX_PH_SHIFT_POS:	31
13:04:50.058 -> TOF_1
13:04:50.058 -> 	RAW:			0xE4
13:04:50.058 -> 	PGA_GAIN:		21 dB
13:04:50.058 -> 	PGA_CTRL:		ON
13:04:50.058 -> 	LNA_CTRL:		ON
13:04:50.058 -> 	LNA_FB:			RESISTIVE
13:04:50.058 -> 	TIMING_REG[9:8]:	0
13:04:50.058 -> TOF_0
13:04:50.058 -> 	RAW:			0x0
13:04:50.058 -> 	TIMING_REG[9:0]:	0
13:04:50.058 -> ERROR_FLAGS
13:04:50.058 -> 	RAW:			0x0
13:04:50.058 -> 	ERR_SIG_WEAK:		0
13:04:50.058 -> 	ERR_NO_SIG:		0
13:04:50.058 -> 	ERR_SIG_HIGH:		0
13:04:50.058 -> TIMEOUT
13:04:50.058 -> 	RAW:			0x4C
13:04:50.058 -> 	FORCE_SHORT_TOF:	ON
13:04:50.058 -> 	SHORT_TOF_BLANK_PERIOD:	16 x T0 -> 200.00 us
13:04:50.058 -> 	ECHO_TIMEOUT:		OFF
13:04:50.058 -> 	TOF_TIMEOUT_CTRL:	128 x T0 -> 1600.00 us
13:04:50.058 -> CLOCK_RATE
13:04:50.058 -> 	RAW:			0x0
13:04:50.058 -> 	CLOCKIN_DIV:		1
13:04:50.058 -> 	AUTOZERO_PERIOD:	64 x T0 -> 800.00 us
13:04:50.058 -> TOF Control:			Short TOF
13:04:50.058 -> Common-mode:			1600.00 us
13:04:50.058 -> Autozero:			800.00 us
13:04:50.058 -> Transmit:			150.00 us
13:04:50.058 -> Mask/Blank:			200.00 us
13:04:50.058 -> Echo listen:			1600.00 us
13:04:50.058 -> End:				25.00 us
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.159 -> timeout 0
...
...
...

With kind regards, Do you think you could please help me in any way?

**Comment by dsuyashrai** [comment]
Hi, 
I am using the TimerOne Library. It has proceeded further now but now there's some other issue. It's showing timeout 0 now.

13:04:49.922 -> -- Starting TDC1000 test --
13:04:50.058 -> TDC1000 init OK
13:04:50.058 -> T0:				12.50 us
13:04:50.058 -> T1:				25.00 us
13:04:50.058 -> TX_CLOCK:			40000.00 Hz
13:04:50.058 -> CONFIG_0
13:04:50.058 -> 	RAW:			0x6
13:04:50.058 -> 	TX_FREQ_DIV:		2
13:04:50.058 -> 	NUM_TX:			6
13:04:50.058 -> CONFIG_1
13:04:50.058 -> 	RAW:			0x40
13:04:50.058 -> 	NUM_AVG:		1
13:04:50.058 -> 	NUM_RX:			0
13:04:50.058 -> CONFIG_2
13:04:50.058 -> 	RAW:			0x22
13:04:50.058 -> 	VCOM_SEL:		INT
13:04:50.058 -> 	MEAS_MODE:		TOF
13:04:50.058 -> 	DAMPING:		ON
13:04:50.058 -> 	CH_SWP:			OFF
13:04:50.058 -> 	EXT_CHSEL:		OFF
13:04:50.058 -> 	CH_SEL:			1
13:04:50.058 -> 	TOF_MEAS_MODE:		2
13:04:50.058 -> CONFIG_3
13:04:50.058 -> 	RAW:			0x4
13:04:50.058 -> 	TEMP_MODE:		REF, RTD1, RTD2
13:04:50.058 -> 	TEMP_RTD_SEL:		PT1000
13:04:50.058 -> 	TEMP_CLK_DIV:		8
13:04:50.058 -> 	BLANKING:		OFF
13:04:50.058 -> 	ECHO_QUAL_THLD:		-220 mV
13:04:50.058 -> CONFIG_4
13:04:50.058 -> 	RAW:			0x1F
13:04:50.058 -> 	RECEIVE_MODE:		SINGLE ECHO
13:04:50.058 -> 	TRIG_EDGE_POLARITY:	RISING
13:04:50.058 -> 	TX_PH_SHIFT_POS:	31
13:04:50.058 -> TOF_1
13:04:50.058 -> 	RAW:			0xE4
13:04:50.058 -> 	PGA_GAIN:		21 dB
13:04:50.058 -> 	PGA_CTRL:		ON
13:04:50.058 -> 	LNA_CTRL:		ON
13:04:50.058 -> 	LNA_FB:			RESISTIVE
13:04:50.058 -> 	TIMING_REG[9:8]:	0
13:04:50.058 -> TOF_0
13:04:50.058 -> 	RAW:			0x0
13:04:50.058 -> 	TIMING_REG[9:0]:	0
13:04:50.058 -> ERROR_FLAGS
13:04:50.058 -> 	RAW:			0x0
13:04:50.058 -> 	ERR_SIG_WEAK:		0
13:04:50.058 -> 	ERR_NO_SIG:		0
13:04:50.058 -> 	ERR_SIG_HIGH:		0
13:04:50.058 -> TIMEOUT
13:04:50.058 -> 	RAW:			0x4C
13:04:50.058 -> 	FORCE_SHORT_TOF:	ON
13:04:50.058 -> 	SHORT_TOF_BLANK_PERIOD:	16 x T0 -> 200.00 us
13:04:50.058 -> 	ECHO_TIMEOUT:		OFF
13:04:50.058 -> 	TOF_TIMEOUT_CTRL:	128 x T0 -> 1600.00 us
13:04:50.058 -> CLOCK_RATE
13:04:50.058 -> 	RAW:			0x0
13:04:50.058 -> 	CLOCKIN_DIV:		1
13:04:50.058 -> 	AUTOZERO_PERIOD:	64 x T0 -> 800.00 us
13:04:50.058 -> TOF Control:			Short TOF
13:04:50.058 -> Common-mode:			1600.00 us
13:04:50.058 -> Autozero:			800.00 us
13:04:50.058 -> Transmit:			150.00 us
13:04:50.058 -> Mask/Blank:			200.00 us
13:04:50.058 -> Echo listen:			1600.00 us
13:04:50.058 -> End:				25.00 us
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.058 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.091 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.125 -> timeout 0
13:04:50.159 -> timeout 0
...
...
...

With kind regards, Do you think you could please help me in any way? It would be very much appreciated and I would be highly grateful to you.
