### ISSUE TITLE
Help setting TDC1000 with Arduino

### ISSUE THREAD

**Issue by suyashrai** [Yveaux/TDC1000#5]
I need help with the setup

**Comment by suyashrai** [comment]
Would you be kind enough to provide the circuit diagram to connect TDC1000 with the Arduino Nano or Arduino UNO?

**Comment by Yveaux** [comment]
I developed the driver using an Arduino Nano.
The pin connections are described at the top of the example file: https://github.com/Yveaux/TDC1000/blob/master/examples/TDC1000_Test/TDC1000_Test.ino#L5
Rest of the lines is regular SPI connection: MISO, MOSI, SCK.

**Comment by meysam-radmanesh** [comment]
> I developed the driver using an Arduino Nano.
> The pin connections are described at the top of the example file: https://github.com/Yveaux/TDC1000/blob/master/examples/TDC1000_Test/TDC1000_Test.ino#L5
> Rest of the lines is regular SPI connection: MISO, MOSI, SCK.
I connected the same pins and connected si5351 to CLKIN and SCL,SCK but didn't get result

**Comment by meysam-radmanesh** [comment]
do you have a schematic?
